const bcrypt = require('bcryptjs');

// In-memory data store for fallback when MongoDB is not connected
const store = {
  users: [],
  appointments: [],
  prescriptions: [],
  reports: [],
  auditLogs: [],
};

const initializeDefaultData = async () => {
  const salt = await bcrypt.genSalt(10);
  const defaultPasswordHash = await bcrypt.hash('MedQ@2026', salt);

  store.users = [
    {
      _id: 'user_patient_1',
      name: 'Sarah Jenkins',
      email: 'patient@medqcare.com',
      password: defaultPasswordHash,
      phone: '+1 (555) 234-5678',
      role: 'patient',
      gender: 'Female',
      dateOfBirth: new Date('1994-06-15'),
      status: 'active',
      profileImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      patientDetails: {
        bloodGroup: 'O+',
        allergies: ['Penicillin', 'Peanuts'],
        medicalHistory: ['Mild Asthma', 'Migraine'],
        emergencyContact: {
          name: 'Robert Jenkins',
          relation: 'Spouse',
          phone: '+1 (555) 876-5432',
        },
      },
      createdAt: new Date('2025-01-10'),
    },
    {
      _id: 'user_doctor_1',
      name: 'Dr. Michael Chen',
      email: 'doctor@medqcare.com',
      password: defaultPasswordHash,
      phone: '+1 (555) 345-6789',
      role: 'doctor',
      gender: 'Male',
      dateOfBirth: new Date('1982-11-20'),
      status: 'active',
      profileImage: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80',
      doctorDetails: {
        specialization: 'Cardiologist & Internal Medicine',
        licenseNumber: 'MD-MED-84920',
        experience: 14,
        qualification: 'MD, FACC, Harvard Med',
        consultationFee: 750,
        rating: 4.9,
        roomNumber: 'OPD-304',
        isOnDuty: true,
        availability: [
          { day: 'Monday', slots: ['09:00 AM', '10:00 AM', '11:30 AM', '02:00 PM', '04:00 PM'] },
          { day: 'Tuesday', slots: ['09:00 AM', '10:30 AM', '01:30 PM', '03:30 PM'] },
          { day: 'Wednesday', slots: ['10:00 AM', '11:30 AM', '02:30 PM', '04:30 PM'] },
          { day: 'Thursday', slots: ['09:00 AM', '11:00 AM', '02:00 PM', '03:30 PM'] },
          { day: 'Friday', slots: ['09:30 AM', '11:30 AM', '01:30 PM', '03:00 PM'] },
        ],
      },
      createdAt: new Date('2024-11-05'),
    },
    {
      _id: 'user_doctor_2',
      name: 'Dr. Aisha Patel',
      email: 'aisha.patel@medqcare.com',
      password: defaultPasswordHash,
      phone: '+1 (555) 456-7890',
      role: 'doctor',
      gender: 'Female',
      dateOfBirth: new Date('1988-04-12'),
      status: 'active',
      profileImage: 'https://images.unsplash.com/photo-1594824813598-a28a30143899?w=150&auto=format&fit=crop&q=80',
      doctorDetails: {
        specialization: 'General Physician & Diabetologist',
        licenseNumber: 'MD-MED-99312',
        experience: 9,
        qualification: 'MBBS, MD (Medicine)',
        consultationFee: 500,
        rating: 4.8,
        roomNumber: 'OPD-102',
        isOnDuty: true,
        availability: [
          { day: 'Monday', slots: ['10:00 AM', '11:00 AM', '03:00 PM', '05:00 PM'] },
          { day: 'Wednesday', slots: ['09:00 AM', '11:00 AM', '02:00 PM', '04:00 PM'] },
          { day: 'Friday', slots: ['10:00 AM', '12:00 PM', '03:00 PM', '05:00 PM'] },
        ],
      },
      createdAt: new Date('2024-12-01'),
    },
    {
      _id: 'user_reception_1',
      name: 'Elena Rostova',
      email: 'reception@medqcare.com',
      password: defaultPasswordHash,
      phone: '+1 (555) 567-8901',
      role: 'reception',
      gender: 'Female',
      status: 'active',
      profileImage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      receptionDetails: {
        department: 'Main Registration Desk & Triage',
        shiftTiming: 'Morning (07:30 AM - 03:30 PM)',
        employeeId: 'MEDQ-REC-007',
      },
      createdAt: new Date('2025-01-02'),
    },
    {
      _id: 'user_admin_1',
      name: 'Administrator Chief',
      email: 'admin@medqcare.com',
      password: defaultPasswordHash,
      phone: '+1 (555) 999-0000',
      role: 'admin',
      gender: 'Male',
      status: 'active',
      profileImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
      adminDetails: {
        accessLevel: 'SuperAdmin',
        department: 'Executive Healthcare Informatics',
        permissions: ['ALL_PERMISSIONS', 'MANAGE_USERS', 'MANAGE_DOCTORS', 'VIEW_AUDIT_LOGS', 'SYSTEM_SETTINGS'],
      },
      createdAt: new Date('2024-10-01'),
    },
  ];

  store.appointments = [
    {
      _id: 'apt_101',
      patientId: 'user_patient_1',
      patientName: 'Sarah Jenkins',
      patientPhone: '+1 (555) 234-5678',
      doctorId: 'user_doctor_1',
      doctorName: 'Dr. Michael Chen',
      specialization: 'Cardiologist & Internal Medicine',
      appointmentDate: new Date(Date.now() + 86400000 * 1), // Tomorrow
      timeSlot: '10:00 AM',
      status: 'confirmed',
      reason: 'Routine Cardiac Follow-up & Blood Pressure Check',
      symptoms: ['Occasional Palpitations', 'Mild Fatigue'],
      tokenNumber: 'CARD-12',
      roomNumber: 'OPD-304',
      consultationFee: 750,
      isPaid: true,
      isCheckedIn: false,
      createdBy: 'patient',
      notes: 'Patient requested morning slot.',
      createdAt: new Date(Date.now() - 86400000 * 2),
    },
    {
      _id: 'apt_102',
      patientId: 'user_patient_1',
      patientName: 'Sarah Jenkins',
      patientPhone: '+1 (555) 234-5678',
      doctorId: 'user_doctor_2',
      doctorName: 'Dr. Aisha Patel',
      specialization: 'General Physician & Diabetologist',
      appointmentDate: new Date(Date.now() - 86400000 * 5),
      timeSlot: '11:00 AM',
      status: 'completed',
      reason: 'Seasonal Viral Fever & Throat Infection',
      symptoms: ['Sore Throat', 'Low Grade Fever'],
      tokenNumber: 'GEN-08',
      roomNumber: 'OPD-102',
      consultationFee: 500,
      isPaid: true,
      isCheckedIn: true,
      checkedInAt: new Date(Date.now() - 86400000 * 5),
      createdBy: 'patient',
      notes: 'Prescription issued. Full recovery advised.',
      createdAt: new Date(Date.now() - 86400000 * 6),
    },
    {
      _id: 'apt_103',
      patientId: 'user_patient_1',
      patientName: 'Sarah Jenkins',
      patientPhone: '+1 (555) 234-5678',
      doctorId: 'user_doctor_1',
      doctorName: 'Dr. Michael Chen',
      specialization: 'Cardiologist & Internal Medicine',
      appointmentDate: new Date(),
      timeSlot: '02:00 PM',
      status: 'in-consultation',
      reason: 'Review ECG and lipid profile results',
      symptoms: ['Chest Tightness after exercise'],
      tokenNumber: 'CARD-04',
      roomNumber: 'OPD-304',
      consultationFee: 750,
      isPaid: true,
      isCheckedIn: true,
      checkedInAt: new Date(),
      createdBy: 'reception',
      notes: 'Walk-in check-in confirmed by Elena.',
      createdAt: new Date(),
    },
  ];

  store.prescriptions = [
    {
      _id: 'rx_501',
      appointmentId: 'apt_102',
      patientId: 'user_patient_1',
      patientName: 'Sarah Jenkins',
      doctorId: 'user_doctor_2',
      doctorName: 'Dr. Aisha Patel',
      doctorSpecialization: 'General Physician & Diabetologist',
      doctorLicense: 'MD-MED-99312',
      diagnosis: 'Acute Upper Respiratory Tract Pharyngitis',
      medicines: [
        {
          name: 'Amoxicillin + Clavulanic Acid 625mg',
          dosage: '1 Tablet',
          frequency: '1-0-1 (After Food)',
          duration: '5 Days',
          instructions: 'Complete full antibiotic course',
        },
        {
          name: 'Paracetamol 650mg (Dolo)',
          dosage: '1 Tablet',
          frequency: 'SOS (When Fever > 100°F)',
          duration: '3 Days',
          instructions: 'Take with full glass of water',
        },
        {
          name: 'Levocetirizine 5mg',
          dosage: '1 Tablet',
          frequency: '0-0-1 (At Bedtime)',
          duration: '5 Days',
          instructions: 'May cause mild drowsiness',
        },
      ],
      testsRecommended: ['Complete Blood Count (CBC)', 'Throat Swab Culture'],
      advice: 'Drink warm water with honey. Avoid cold beverages and air conditioner direct draft. Rest for 3 days.',
      followUpDate: new Date(Date.now() + 86400000 * 7),
      date: new Date(Date.now() - 86400000 * 5),
      createdAt: new Date(Date.now() - 86400000 * 5),
    },
  ];

  store.reports = [
    {
      _id: 'rep_201',
      patientId: 'user_patient_1',
      patientName: 'Sarah Jenkins',
      doctorId: 'user_doctor_1',
      doctorName: 'Dr. Michael Chen',
      title: 'Comprehensive Lipid Profile & Lipid Biomarkers',
      category: 'Blood Test',
      reportDate: new Date(Date.now() - 86400000 * 3),
      fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
      fileName: 'Lipid_Profile_Report_2026.pdf',
      fileSize: '1.4 MB',
      labName: 'MedQ Central Diagnostics Lab (NABL Accredited)',
      summary: 'HDL Cholesterol levels are optimal. LDL is mildly borderline. Dietary adjustments advised.',
      metrics: [
        { parameter: 'Total Cholesterol', value: '192', unit: 'mg/dL', referenceRange: '< 200', status: 'Normal' },
        { parameter: 'HDL (Good) Cholesterol', value: '58', unit: 'mg/dL', referenceRange: '> 50', status: 'Normal' },
        { parameter: 'LDL (Bad) Cholesterol', value: '118', unit: 'mg/dL', referenceRange: '< 100', status: 'Borderline' },
        { parameter: 'Triglycerides', value: '135', unit: 'mg/dL', referenceRange: '< 150', status: 'Normal' },
      ],
      status: 'Verified',
      createdAt: new Date(Date.now() - 86400000 * 3),
    },
    {
      _id: 'rep_202',
      patientId: 'user_patient_1',
      patientName: 'Sarah Jenkins',
      doctorId: 'user_doctor_2',
      title: 'Complete Blood Count (CBC) with Differential',
      category: 'Pathology',
      reportDate: new Date(Date.now() - 86400000 * 5),
      fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
      fileName: 'CBC_Report_Sarah_Jenkins.pdf',
      fileSize: '890 KB',
      labName: 'MedQ Central Diagnostics Lab (NABL Accredited)',
      summary: 'All leukocyte parameters are within healthy range. Platelets adequate.',
      metrics: [
        { parameter: 'Hemoglobin', value: '13.6', unit: 'g/dL', referenceRange: '12.0 - 15.5', status: 'Normal' },
        { parameter: 'WBC Total Count', value: '7,400', unit: '/mcL', referenceRange: '4,500 - 11,000', status: 'Normal' },
        { parameter: 'Platelets', value: '280,000', unit: '/mcL', referenceRange: '150,000 - 450,000', status: 'Normal' },
      ],
      status: 'Verified',
      createdAt: new Date(Date.now() - 86400000 * 5),
    },
  ];

  store.auditLogs = [
    {
      _id: 'log_01',
      action: 'SYSTEM_INITIALIZATION',
      user: 'Administrator Chief',
      role: 'admin',
      details: 'MedQ Care Platform Services booted successfully.',
      ip: '127.0.0.1',
      timestamp: new Date(),
    },
    {
      _id: 'log_02',
      action: 'USER_LOGIN',
      user: 'Dr. Michael Chen',
      role: 'doctor',
      details: 'Doctor session authenticated via JWT token.',
      ip: '192.168.1.45',
      timestamp: new Date(Date.now() - 3600000),
    },
    {
      _id: 'log_03',
      action: 'PATIENT_CHECKIN',
      user: 'Elena Rostova',
      role: 'reception',
      details: 'Patient Sarah Jenkins marked checked-in for Dr. Michael Chen (OPD-304).',
      ip: '192.168.1.10',
      timestamp: new Date(Date.now() - 1800000),
    },
  ];
};

initializeDefaultData();

module.exports = {
  store,
  initializeDefaultData,
};
